#include <inttypes.h>
#include "internal.h"
void eval_grammar(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_ws(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_wsp(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_rule(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_name(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_body(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_alt(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_seq(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_operator(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_prefix(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_and(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_not(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_postfix(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_star(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_plus(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_option(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_group(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_final(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_nonterminal(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_literal(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_cclass(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_code(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void eval_dot(memo_state_t* state, uint8_t* text, uint32_t text_length, uint32_t pos, eval_return_t* ret);
void semantic_action_0(context_t* context);
void alias_allocs_0(context_t* context);
void alias_frees_0(context_t* context);
void semantic_action_18(context_t* context);
void alias_allocs_18(context_t* context);
void alias_frees_18(context_t* context);
void semantic_action_31(context_t* context);
void alias_allocs_31(context_t* context);
void alias_frees_31(context_t* context);
void semantic_action_32(context_t* context);
void alias_allocs_32(context_t* context);
void alias_frees_32(context_t* context);
void semantic_action_40(context_t* context);
void alias_allocs_40(context_t* context);
void alias_frees_40(context_t* context);
void semantic_action_47(context_t* context);
void alias_allocs_47(context_t* context);
void alias_frees_47(context_t* context);
void semantic_action_54(context_t* context);
void alias_allocs_54(context_t* context);
void alias_frees_54(context_t* context);
void semantic_action_61(context_t* context);
void alias_allocs_61(context_t* context);
void alias_frees_61(context_t* context);
void semantic_action_69(context_t* context);
void alias_allocs_69(context_t* context);
void alias_frees_69(context_t* context);
void semantic_action_73(context_t* context);
void alias_allocs_73(context_t* context);
void alias_frees_73(context_t* context);
void semantic_action_80(context_t* context);
void alias_allocs_80(context_t* context);
void alias_frees_80(context_t* context);
void semantic_action_84(context_t* context);
void alias_allocs_84(context_t* context);
void alias_frees_84(context_t* context);
void semantic_action_88(context_t* context);
void alias_allocs_88(context_t* context);
void alias_frees_88(context_t* context);
void semantic_action_96(context_t* context);
void alias_allocs_96(context_t* context);
void alias_frees_96(context_t* context);
void semantic_action_102(context_t* context);
void alias_allocs_102(context_t* context);
void alias_frees_102(context_t* context);
void semantic_action_108(context_t* context);
void alias_allocs_108(context_t* context);
void alias_frees_108(context_t* context);
void semantic_action_110(context_t* context);
void alias_allocs_110(context_t* context);
void alias_frees_110(context_t* context);
void semantic_action_111(context_t* context);
void alias_allocs_111(context_t* context);
void alias_frees_111(context_t* context);
void semantic_action_112(context_t* context);
void alias_allocs_112(context_t* context);
void alias_frees_112(context_t* context);
void semantic_action_113(context_t* context);
void alias_allocs_113(context_t* context);
void alias_frees_113(context_t* context);
void semantic_action_115(context_t* context);
void alias_allocs_115(context_t* context);
void alias_frees_115(context_t* context);
void semantic_action_121(context_t* context);
void alias_allocs_121(context_t* context);
void alias_frees_121(context_t* context);
void semantic_action_122(context_t* context);
void alias_allocs_122(context_t* context);
void alias_frees_122(context_t* context);
void semantic_action_136(context_t* context);
void alias_allocs_136(context_t* context);
void alias_frees_136(context_t* context);
void semantic_action_164(context_t* context);
void alias_allocs_164(context_t* context);
void alias_frees_164(context_t* context);
